#!/bin/bash

# Build script for Falkor Mudlet package
# Recursively concatenates all .lua files from src/ into a single build file

set -e  # Exit on error

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${SCRIPT_DIR}/src"
BUILD_DIR="${SCRIPT_DIR}/build"
OUTPUT_FILE="${BUILD_DIR}/achaea.lua"

# Create build directory if it doesn't exist
mkdir -p "${BUILD_DIR}"

# Check if src directory exists
if [ ! -d "${SRC_DIR}" ]; then
    echo "Error: src/ directory not found!"
    exit 1
fi

# Start with a header comment
cat > "${OUTPUT_FILE}" << EOF
-- Falkor Combat Script for Mudlet/Achaea
-- Built from source files in src/
-- DO NOT EDIT THIS FILE - Edit files in src/ and rebuild
-- Build date: $(date)

EOF

# Define explicit load order (files will be loaded in this order)
LOAD_ORDER=("log.lua" "player.lua" "butterflies.lua" "rats.lua" "main.lua")

# Function to add a file to the build output
add_file_to_build() {
    local file="$1"
    echo "-- ============================================" >> "${OUTPUT_FILE}"
    echo "-- Source: ${file#${SRC_DIR}/}" >> "${OUTPUT_FILE}"
    echo "-- ============================================" >> "${OUTPUT_FILE}"
    echo "" >> "${OUTPUT_FILE}"
    cat "${file}" >> "${OUTPUT_FILE}"
    echo "" >> "${OUTPUT_FILE}"
    echo "" >> "${OUTPUT_FILE}"
}

# Process files in explicit order first
for filename in "${LOAD_ORDER[@]}"; do
    file="${SRC_DIR}/${filename}"
    if [ -f "${file}" ]; then
        add_file_to_build "${file}"
    fi
done

# Find any remaining .lua files not in the load order and add them alphabetically
# This allows for future modules to be added without modifying the build script
find "${SRC_DIR}" -type f -name "*.lua" -print0 | sort -z | while IFS= read -r -d '' file; do
    filename=$(basename "${file}")
    # Check if this file was already processed in the load order
    already_processed=false
    for ordered_file in "${LOAD_ORDER[@]}"; do
        if [ "${filename}" = "${ordered_file}" ]; then
            already_processed=true
            break
        fi
    done
    
    if [ "${already_processed}" = false ]; then
        add_file_to_build "${file}"
    fi
done

echo "Build complete!"
echo "Output: ${OUTPUT_FILE}"
echo ""
echo "File count: $(find "${SRC_DIR}" -type f -name "*.lua" | wc -l | tr -d ' ') .lua files concatenated"
echo "Output size: $(wc -l < "${OUTPUT_FILE}" | tr -d ' ') lines"
